"""empty message

Revision ID: 9530e35ee133
Revises: 
Create Date: 2022-10-26 04:06:47.346066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9530e35ee133'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.TEXT(), nullable=False))
    op.add_column('users', sa.Column('hash_password', sa.TEXT(), nullable=False))
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), nullable=False))
    op.drop_index('ix_users_login', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_login', 'users', ['login'], unique=False)
    op.drop_column('users', 'confirmed')
    op.drop_column('users', 'hash_password')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
